### ISSUE TITLE
Be able to set the correct winred.exe name for cross compilation

### ISSUE THREAD

**Issue by lamogui** [mxre/winres#13]
Scenario: under linux ubuntu, 
 - install the target x86_64-pc-windows-gnu `rustup target add x86_64-pc-windows-gnu`
 - create an hello world crate with a build script using winres that just compile the winres file
 - configure the .cargo/config file with
```toml
[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc" 
```
 - try to build the package with `cargo build --target=x86_64-pc-windows-gnu` the build fail with the error 
```
--- stderr
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

This non versatile error mean you tried to invoke windres.exe but under linux this executable is named `x86_64-w64-mingw32-windres` 

you should add an option to specify the executable name

**Comment by kdar** [comment]
I ran into this problem using Windows Subsystem for Linux targeting x86_64-pc-windows-gnu. My solution was to make bash scripts in the root directory, like:

windres.exe
```
#!/bin/bash

x86_64-w64-mingw32-windres "$@"
```
and then this is in my build.rs:
```
use std::error::Error;
use std::env;

fn main() -> Result<(), Box<Error>> {
  let p = env::var("PATH").unwrap();
  env::set_var("PATH", format!("{}:{}", env!("CARGO_MANIFEST_DIR"), p));
  let mut res = winres::WindowsResource::new();
  res.set_toolkit_path(env!("CARGO_MANIFEST_DIR"));
  // ...
  res.compile()?;

  Ok(())
}
```

Not ideal but works for now.

**Comment by mxre** [comment]
I myself have never used mingw to cross compile from Linux to Windows. I will look into making the Toolkit configuration more adaptable by either detection cross complication (PR welcome!) or by providing a call to set the resource compiler in `build.rs`.
