### ISSUE TITLE
Changing icon resource doesn't update exe

### ISSUE THREAD

**Issue by mon** [mxre/winres#17]
I honestly wouldn't be surprised if windows explorer was caching the icon. Even a `cargo clean` before rebuilding gives me the old icon. Anything funky with GUIDs that could cause it? I don't know anything about resources.

**Comment by armoha** [comment]
It is due to icon cache of Windows. You can check file properties or clean icon cache to refresh icon.

**Comment by mon** [comment]
Thanks for the update! A pity it's a Windows limitation, but at least the icon cache clear is a workaround.
