### ISSUE TITLE
Default icon id should be 32512

### ISSUE THREAD

**Issue by lucasfernog** [mxre/winres#28]
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-loadicona

When using the LoadIcon API, IDI_APPLICATION looks for id 32512: MAKEINTRESOURCE(32512)

**Comment by mxre** [comment]
Every Example I've seen uses id 1 for the program icon in the resource files. Additionally I've looked at several exes on my disks and almost all use 1 as the primary icon id.
You can use LoadIcon with the Id 1, or alternatively add an Icon with the Id of 32512 using `WindowResource:set_icon_with_id`

**Comment by zedseven** [comment]
All executables built by Visual Studio/.NET with embedded icons use the icon ID 32512.
I would consider Visual Studio to be a canonical source of Microsoft standards when it comes to default icon ID.

![image](https://user-images.githubusercontent.com/25164338/135158017-a16546a5-dff8-4961-8bcb-de4025f0e1c6.png)
(using IconViewer to check icon ID)

**Comment by GeeLaw** [comment]
You might be interested in Raymond Chen's explanation on this: https://devblogs.microsoft.com/oldnewthing/20250423-00/?p=111106
