### ISSUE TITLE
How about other targets?

### ISSUE THREAD

**Issue by hlavaatch** [mxre/winres#29]
Is there a way to put resources into other binaries except main.rs?
stuff in src/bin, [[bin]] on Cargo.toml ...
It would be desirable to be able to handle these separately..

**Comment by mxre** [comment]
I think this is currenly not possible as the build.rs script is only declared on a per-crate level (in the toml package node) and, as far as I can tell cargo does not pass anny onformation on the targets to the build script. winres only sets additional linker flags, which are then used by cargo in the creation of the executable
