### ISSUE TITLE
Newlines in XML attributes cause spaces to be deleted - "side-by-side configuration is incorrect"

### ISSUE THREAD

**Issue by mon** [mxre/winres#31]
With a standard manifest entry such as the Common Controls dependency, I spread it over many lines as it is easier to read:
```xml
<assemblyIdentity
  type="win32"
  name="Microsoft.Windows.Common-Controls"
  version="6.0.0.0"
  processorArchitecture="*"
  publicKeyToken="6595b64144ccf1df"
  language="*"
/>
```

However, due to the handling of the XML manifest:
```rust
                for line in manf.lines() {
                    writeln!(f, "\"{}\"", escape_string(line.trim()))?;
                }
```
The whitespace is trimmed and the resulting XML snippet has no whitespace:
```xml
<assemblyIdentitytype="win32"name="Microsoft.Windows.Common-Controls"version="6.0.0.0"processorArchitecture="*"publicKeyToken="6595b64144ccf1df"language="*"/>
```

Understandably, this breaks the build with the error: `The application has failed to start because its side-by-side configuration is incorrect.`

Ideally, whitespace should be preserved, though I'm not sure if this will break something else which is why this is a bug instead of a PR.

**Comment by mxre** [comment]
I am not an expert on application manifests and I thought that add each line seperatly to the resource file would cover such an eventuality. I commit a version that adds spaces before and after each line, but I'm unsure if this introduces new bugs in oddly formated files (normaly for XML it should not matter)
