### ISSUE TITLE
Question about ProductVersion and FileVersion

### ISSUE THREAD

**Issue by Boscop** [mxre/winres#9]
FileVersion is not listed in the supported variables of this crate, but my exe still has a FileVersion (0.1.0.0). Is it set by cargo based on the version set it Cargo.toml? Or also set by this crate?

Shouldn't the ProductVersion always be the same as FileVersion when publishing the exe?

How can I keep the ProductVersion (and FileVersion) automatically the same as the version set in Cargo.toml? :)

**Comment by Boscop** [comment]
Thanks. Btw, should the version be in binary or decimal format? MS docs say binary but it seems to work when I set it in decimal.

**Comment by mxre** [comment]
If you refer to the version field in Cargo.toml `package` section, look at the Cargo.toml [Documentation](https://doc.rust-lang.org/cargo/reference/manifest.html#the-version-field)

If you want to set the Version Information manually you need to generate a `u64` out of the 4 `u16` components in the version:

So `a.b.c.d` is 
```rust
let wres = WindowsResource::new();
let mut version = 0 as u64;
version |= a << 48;
version |= b << 32;
version |= c << 16;
version |= d
wres.set_version_info(VersionInfo::FILEVERSION, version);
wres.set_version_info(VersionInfo::PRODUCTVERSION, version);
```

The String Fields (set by `package.metadata.winres` in Cargo.toml or using `WindowsResource.set()`) can be any unicode string, but are usually the same as the numeric ones.
